server:
  port: 8080

spring:
  data:
    mongodb:
      database: example

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.7

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    host: localhost
    port: 27017
    database: example
    write-concern:
      journal: false
    read-concern: local



#  datasource:
#    url: jdbc:h2:mem:maindb
#  sql:
#    init:
#      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        trace: true
#        web-allow-others: true
